microsoft/vscode-iot-workbench

- test/stub.ts
> fix no initializer issue in test

- src/exampleExplorer.ts
related issue: https://github.com/Microsoft/vscode-iot-workbench/issues/126#issuecomment-372583518
> fix path issue for example

- src/Models/AZ3166Device.ts
related issue: https://github.com/Microsoft/vscode-iot-workbench/issues/197
> fix sketch file name issue

- package.json
Related issue: https://github.com/Microsoft/vscode-iot-workbench/issues/194
> change activate

- resources/boardlist.json
- resources/devkit/template.json
- resources/iotbutton/template.json
- src/ArduinoPackageManager.ts
- src/DeviceOperator.ts
- src/Models/AZ3166Device.ts
- src/Models/Interfaces/Device.ts
- src/Models/IoTButtonDevice.ts
- src/Models/IoTProject.ts
- src/boardProvider.ts
- src/constants.ts
- src/projectInitializer.ts
Currently, the http request to send/receive data from Iot button is not implemented
> Add the support of Azure IoT button 

- src/Models/IoTButtonDevice.ts
Also use IoT button instead of Azure IoT Button
> Fix the problem of setting user data 

- package.json
https://github.com/Microsoft/vscode-iot-workbench/issues/279
> add 'Azure' category into package.json

- README.md
Update docs for contributing examples
> Update docs for contributing examples 

- docs/iot-devkit/devkit-ota.md
* Change the tile
* Fix layout
> Update the OTA doc

- src/Models/Interfaces/CommandItem.ts
- src/extension.ts
Now the commands can be filtered by the device id of the workspace.
> add filter command by device option

- docs/iot-devkit/devkit-shakeshake.md
This is trivial change, updated the linked asset path.
Thanks!
> Update shake a tweet sample linked asset. Fixes #421

- package.json
- src/Models/ArduinoDeviceBase.ts
- src/Models/IoTProject.ts
- src/projectInitializer.ts
1. Rename the command to  'create new project'
2. Change the order for creating project.
3. Don't ask user to input sketch name
4. use project name as the workspace name
> Refactor the code for creating new project

- docs/iot-devkit/devkit-mqtt-client.md
Instructions on how to open the palette.
> Adding in command shortcut

- docs/iot-devkit/devkit-get-started.md
Fix for #580. Let me know if you want me to add a screenshot as well.
> Adding missing Arduino extension

- docs/esp32/esp32-state.md
Remove "Cloud: " from "Azure IoT Device Workbench: Cloud: Provision Azure Services..."
> Remove "Cloud: "

- src/Models/AZ3166Device.ts
- src/Models/AzureFunctions.ts
update error message and disable generating platform.local.txt during project load
> update error message and disable generating platform.local.txt 

- src/AzureOperator.ts
- src/DeviceOperator.ts
- src/Models/Interfaces/ProjectType.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/extension.ts
- src/projectInitializer.ts
To support both container project and workspace project
> Create base class for IoT Project

- resources/templates/ansic_cmake_connectionstring/CMakeLists.txt
- resources/templates/ansic_cmake_iotcsaskey/CMakeLists.txt
This change is coming from c sdk which avoid link error under Linux
>   Add iothub_client_mqtt_transport into cmake file

- src/DigitalTwin/CodeGeneratorCore.ts
- src/DigitalTwin/DeviceModelOperator.ts
Show error and point user to open the company model repository
> Abort codegen if can't find interface.

- README.md
Add PnP part for public preview.
> PnP content

- resources/templates/ansic_cmake_connectionstring/Readme.md
- resources/templates/ansic_cmake_iotcsaskey/Readme.md
- resources/templates/ansic_vs_connectionstring/Readme.md
- resources/templates/ansic_vs_iotcsaskey/Readme.md
Fix bug: https://dev.azure.com/mseng/VSIoT/_workitems/edit/1584336
> Fix wording per Stefan's feedback

- .travis.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- resources/templates/ansic_devkit_connectionstring/main.ino
- resources/templates/ansic_devkit_iotcsaskey/main.ino
- resources/templates/devicemodel/sample.capabilitymodel.json
- src/AzureOperator.ts
- src/DeviceOperator.ts
- src/DigitalTwin/CodeGeneratorCore.ts
- src/DigitalTwin/DigitalTwinCodeGen/Interfaces/AnsiCCodeGeneratorBase.ts
- src/DigitalTwin/DigitalTwinConstants.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/extension.ts
- src/utils.ts
- test/stub.ts
1. Sync with master
2. Tiny fix: Function rename
> Sync with master branch

- package.json
- resources/templates/ansic_devkit_connectionstring/main.ino
- resources/templates/ansic_devkit_iotcsaskey/main.ino
Update pnp template.
Remove usless commands.
> Update pnp template.

- CHANGELOG.md
- README.md
@liydu - here are some suggested updates to the Readme and Changelog files
> Review Readme and Changelog

- resources/templates/ansic_cmake_connectionstring/CMakeLists.txt
- resources/templates/ansic_cmake_iotcsaskey/CMakeLists.txt
- src/DigitalTwin/DigitalTwinCodeGen/AnsiCCodeGeneratorImplCMake.ts
Changes in this PR:
- Remove GLOB micro in CMakeLists.txt and include generated files explicitly.
- Expand compileAsC99 micro whish is defined in device SDK.
> Improve CMakeLists.txt that generated for PnP Cmake project

- docs/iot-devkit/devkit-shakeshake.md
- docs/iot-devkit/devkit_door_monitor.md
- resources/templates/boardlist.json
- src/exampleExplorer.ts
- src/usbDetector.ts
- views/example.html
change mxchip devkit sample page
> Devkit Samples

- src/Models/AZ3166Device.ts
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1597670
> Remind user to restart VS Code after install Arduino IDE

- package-lock.json
- package.json
- src/Models/RaspberryPiDevice.ts
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1605108
> Fix upload folder

- src/Models/IoTContainerizedProject.ts
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1597804
> Fix customize container wording

- package.json
- src/Models/RemoteExtension.ts
- src/usbDetector.ts
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1613235
> Compatible with vs 1.39

- package.json
- src/Models/RemoteExtension.ts
- src/usbDetector.ts
Pre-action to merge container back to master.
> Sync with master

- resources/templates/arm7/Dockerfile
- resources/templates/arm8/Dockerfile
- resources/templates/x86/Dockerfile
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1615941
> Fix ubuntu compatibility: chmod bash script before execution

- resources/templates/arm7/build.sh
- resources/templates/arm8/build.sh
- resources/templates/embedded_linux/CMakeLists.txt
- resources/templates/x86/build.sh
Fix CMakeLists.txt to integarte with latest SDK.
> Fix CMakeLists.txt to integarte with latest SDK.

- src/Models/ArduinoDeviceBase.ts
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1637535
> Fix c_cpp_properties.json auto-refresh

- src/Models/AZ3166Device.ts
Reverts microsoft/vscode-iot-workbench#776
> Revert "Serialport"

- package.json
- scripts/modifyConfigIfRCVersion.js
The origin aikey resource is removed from cloud. Create a new application insights service and replace the aikey.
> Update test aikey

- src/AzureOperator.ts
- src/DigitalTwin/CodeGeneratorCore.ts
- src/DigitalTwin/DigitalTwinCodeGen/Interfaces/AnsiCCodeGenerator.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/AzureFunctions.ts
- src/Models/AzureUtility.ts
- src/Models/ContainerDeviceBase.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/Models/RemoteExtension.ts
- src/ProjectEnvironmentConfiger.ts
- src/common/Commands.ts
- src/constants.ts
- src/exampleExplorer.ts
- src/extension.ts
- src/nsat.ts
- src/projectInitializer.ts
- src/telemetry.ts
- src/usbDetector.ts
- src/utils.ts
- test/Device.test.ts
1. Refactor telemetry worker to be singleton.
2. Remove redundant code.
3. Refactor command initialization in `extension.ts`.
> Code refactor

- src/AzureOperator.ts
- src/DigitalTwin/CodeGeneratorCore.ts
- src/DigitalTwin/DigitalTwinUtility.ts
- src/IoTSettings.ts
- src/Models/AZ3166Device.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/AzureFunctions.ts
- src/Models/ContainerDeviceBase.ts
- src/Models/CosmosDB.ts
- src/Models/Esp32Device.ts
- src/Models/Interfaces/Component.ts
- src/Models/Interfaces/Device.ts
- src/Models/IoTButtonDevice.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTHub.ts
- src/Models/IoTHubDevice.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/Models/RaspberryPiDevice.ts
- src/Models/RemoteExtension.ts
- src/Models/StreamAnalyticsJob.ts
- src/ProjectEnvironmentConfiger.ts
- src/constants.ts
- src/exampleExplorer.ts
- src/exceptionHelper.ts
- src/extension.ts
- src/projectInitializer.ts
- src/telemetry.ts
- src/utils.ts
- test/Device.test.ts
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1652616
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1648990
> [Code Refactor] Error handling

- src/DigitalTwin/CodeGeneratorCore.ts
- src/DigitalTwin/DigitalTwinCodeGen/Interfaces/AnsiCCodeGenerator.ts
- src/FileUtility.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/AzureComponentConfig.ts
- src/Models/AzureFunctions.ts
- src/Models/CosmosDB.ts
- src/Models/Interfaces/Component.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTHub.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/Models/StreamAnalyticsJob.ts
- src/ProjectEnvironmentConfiger.ts
- src/projectInitializer.ts
- src/utils.ts
Code refactor:
1. Break long functions into small functions.
2. Set `projectRootPath`, `deviceRootPath`, `iotworkbenchProjectFile` as class properties. Change the way to construct and create project.
3. Add comments.
4. Rename functions for better readbility.
5. Remove useless code.
> [Code refactor] workbench project create / load

- package-lock.json
- src/DigitalTwin/DigitalTwinCodeGen/Interfaces/AnsiCCodeGenerator.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/AzureFunctions.ts
- src/Models/RemoteExtension.ts
- src/common/Commands.ts
- src/extension.ts
- src/nsat.ts
- src/utils.ts
1. The former reopen in container api `openindocker.reopenInContainer` reopen has been out of date. Replace it with the valid `remote-containers.reopenInContainer`.
2. Refine command constants.
> [Bug fix] Fix reopen api

- package.json
- resources/templates/platformlist.json
- resources/templates/templates.json
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/ProjectEnvironmentConfiger.ts
- src/common/Commands.ts
- src/constants.ts
- src/utils.ts
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1652089
> Configure project environment command flow adjustment

- package-lock.json
- src/Models/ArduinoDeviceBase.ts
- src/Models/ContainerDeviceBase.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/ProjectEnvironmentConfiger.ts
- src/extension.ts
- src/projectInitializer.ts
- src/telemetry.ts
- src/utils.ts
1. Tidy up telemetry context content.
2. Insert `projectHostType` in telemetry when construct project.
3. Remove duplicate code.
> Tidy up telemetry context content

- src/Models/IoTWorkspaceProject.ts
Bug fix: https://dev.azure.com/mseng/VSIoT/_workitems/edit/1659781
> Fix azure function

- azure-pipelines.yml
- scripts/updateConfig.js
Move from travis ci to azure pipeline.
Update in master branch.
> Move from travis ci to azure pipeline in master branch

- azure-pipelines.yml
Add "run credscan" step for windows in azure pipeline.
> run credscan in CI/CD

- src/DigitalTwin/pnp/src/intelliSense/digitalTwinConstants.ts
- src/DigitalTwin/pnp/src/intelliSense/intelliSenseUtility.ts
make @context support both array and string for PnP IntelliSense
> fix: pnp context value support both array and string

- scripts/updateConfig.js
Remove useless code from script to fix nightly build.
> Fix nightly build script

- resources/pnp/definitions/constraint.json
- src/DigitalTwin/pnp/src/intelliSense/digitalTwinCompletionItemProvider.ts
- src/DigitalTwin/pnp/src/intelliSense/digitalTwinConstants.ts
- src/DigitalTwin/pnp/src/intelliSense/digitalTwinDiagnosticProvider.ts
- src/DigitalTwin/pnp/src/intelliSense/digitalTwinGraph.ts
- src/DigitalTwin/pnp/src/intelliSense/digitalTwinHoverProvider.ts
- src/DigitalTwin/pnp/src/intelliSense/intelliSenseUtility.ts
- src/DigitalTwin/pnp/src/modelRepository/modelRepositoryManager.ts
- src/DigitalTwin/pnp/src/view/ui.ts
- src/extension.ts
- tsconfig.json
- add framework code to support multiple DTDL versions
- apply version rules to diagnostics and auto-completion
- fix bug of diagnostic is not available for the active file when VSCode start
- remove unused parameters for initDigitalTwinCommand
> Support multiple versions for PnP IntelliSense

- src/DigitalTwin/pnp/src/intelliSense/digitalTwinConstants.ts
- src/DigitalTwin/pnp/src/intelliSense/digitalTwinGraph.ts
- Interface Instance is renamed to Component.
- context value of v2 is "http://azure.com/v2/contexts/Model.json"
> feat: add DTDL v2 definition change

- __mocks__/vscode.js
- test/digitalTwin/digitalTwinDiagnosticProvider.test.ts
- test/digitalTwin/intelliSenseUtility.test.ts
- test/resources/interface_v1.json
- test/resources/invalid_context.json
- test/resources/invalid_type.json
- test/testUtility.ts
- setup test mechanism for testing PnP IntelliSense by files.
- add test case examples for diagnostics and intelliSense utility.
> test: add test case of diagnostic for PnP IntelliSense

- .vscodeignore
- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.14.0

- CHANGELOG.md
- package-lock.json
- package.json
Update version and change log for release 0.15.0
> Update version and change log

- CHANGELOG.md
- package-lock.json
- package.json
Merge release v0.15.0 to develop branch
> Merge release v0.15.0 to develop branch

- package-lock.json
- package.json
- src/extension.ts
- tsconfig.json
https://dev.azure.com/mseng/VSIoT/_workitems/edit/1754338
> disable pnp function in workbench
