microsoft/vscode-iot-workbench

- src/Models/AZ3166Device.ts
The users can now config UDS of their devices when they are using DevKit.
The input string will be checked and only valid UDS number is allowed. (The string can begin with '0x', '0X' or the first number of UDS)
> add UDS config

- src/Models/AZ3166Device.ts
Fix typo - latest 
`Unable to find the Arduino package path, please install the lastest Arduino package for Devkit.`
to 
`Unable to find the Arduino package path, please install the latest Arduino package for Devkit.`
> Fix typo - latest

- src/Models/AZ3166Device.ts
The arduino package path is currently only defined for windows and mac os, which prevents the extension from being fully usable while developing on a linux platform. The fix is to simply add the required path for linux.
> Add the arduino package path for linux platforms

- src/Models/AzureFunctions.ts
Adding resource group for creating function app would cause storage creation failed.
> Rollback the change for resource group support when creating azure functions app

- docs/iot-devkit.md
The "/Application" is an incorrect path to Arduino IDE.
> Correct macOS Arduino path in docs file

- docs/iot-devkit/devkit-get-started.md
The path to the MacOS Applications folder for the properties JSON file has been corrected to `Applications`
> Correcting Mac Applications path

- docs/iot-devkit/devkit-mqtt-client.md
The previous link was not linking to the correct header, and was instead just linking to the top of the get started page. This minor fix links to the correct header.
> Fixing the "Open serial monitor" link

- resources/templates/devicemodel/sample.capabilitymodel.json
There is a issue on platform side, that sdk can't work properly with AICS if a defice has ModelDefinition interface.
> Remove the ModelDefinition from default DCM template.

- .github/workflows/stale-issues.yml
If an issue with label `need more info` has no activities in recent 7 days and it's last updated by collaborators, `stale` label will be added to the issue with comment.
If an issue is labeled `stale` and has no activities in next 3 days, the issue will be closed.
> Add workflow to mark and close stale issues

- .github/workflows/need-attention-issues.yml
If an issue is last updated by users (non-collaborator) and has no activities in 3 days, `need attention` label will be added to attract attention. Further notification will be sent based on the label.
> Add workflow to pickup issues that need attention

- .travis.yml
- scripts/modifyConfigIfRCVersion.js
Rename rc extension name to "Test OWL Project" to avoid being discovery by users searching "iot" or "workbench".
> Rename rc extension name

- devicedevex_dockerfiles/public/iot-device-cube-1.0.4/azure-c-sdk-public-preview-cross-toolchain-arm32/Dockerfile
Update iot-device-cube-1.0.4:azure-c-sdk-public-preview-cross-toolchain-arm32 lib version to fix armv7 segmentation fault
> Fix armv7 segmentation fault

- package.json
- src/DigitalTwin/CodeGeneratorCore.ts
- src/DigitalTwin/DigitalTwinCodeGen/Interfaces/AnsiCCodeGenerator.ts
- src/IoTSettings.ts
- src/Models/AZ3166Device.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/Esp32Device.ts
- src/common/Commands.ts
- src/constants.ts
- src/exampleExplorer.ts
- src/extension.ts
- src/projectInitializer.ts
- src/usbDetector.ts
- src/utils.ts
- views/example.html
- views/example.js
1. Refactor IoTWorkbenchSettings to be singleton.
2. Replace os string 'win32'/'linux'/'darwin' with constants.
3. Fix auto pop up landing page: Only pop up when user first install iot workbench extension.
> Fix auto popup landing page

- package-lock.json
- src/extension.ts
- src/telemetry.ts
- src/usbDetector.ts
Create telemetry context inside function `callCommandWithTelemetry()` so that each command's telemetryContext can be distinct.
> Fix telemetry context

- src/CancelOperationError.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/ContainerDeviceBase.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTWorkspaceProject.ts
- src/ProjectEnvironmentConfiger.ts
- src/utils.ts
1. Fix auto-configure project env bug: when iot workbench project does not have ".vscode/tasks.json" file, pop up to ask to configure project environment and auto configure according to project platform type.
2. Fix workspace config file name bug: worspace config file path will be initialized in `load()` and `create()` methods respectively.
3. Fix typo
> Bugs fix: auto configure; worspace config file name

- .travis.yml
- CHANGELOG.md
- package.json
- src/DigitalTwin/CodeGeneratorCore.ts
- src/Models/IoTWorkspaceProject.ts
- src/utils.ts
1. Tag nightly build and rc version as `pre-release` in release page.
2. Update version number to `0.110-rc`
3. Update nightly build vsce token as iotdevexbuild  vsce token (`VSCE_TEST_TOKEN`).
4. Ignore warning message when init load.
> Merge v0.11.0-rc back to develop branch

- .travis.yml
Temperately remove travis ci emial notification and will add it when applying azure pipeline.
> Remove Travis CI notification

- src/Models/AZ3166Device.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/AzureFunctions.ts
- src/Models/ContainerDeviceBase.ts
- src/Models/Esp32Device.ts
- src/Models/Interfaces/Component.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTHub.ts
- src/Models/IoTHubDevice.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/Models/RemoteExtension.ts
- src/ProjectEnvironmentConfiger.ts
- src/utils.ts
In TypeScript, usage of `foreach` should be careful. If function inside `foreach` is asynchronous, `foreach` will not wait until all items are finished. (See [Reference](https://lavrton.com/javascript-loops-how-to-handle-async-await-6252dd3c795/)).
this PR:
1. Fix foreach with async functions. Change to `Promise.all()`. Fix the [bug](https://dev.azure.com/mseng/VSIoT/_workitems/edit/1679203).
2. Change `checkPrerequisite()` function to return `Promise<void>` instead of `Promise<boolean>`. User will get error message when operation failed for not finding dependent extensions.
> Fix foreach bug

- package-lock.json
- src/DigitalTwin/CodeGeneratorCore.ts
- src/Models/Apis.ts
- src/Models/ArduinoDeviceBase.ts
- src/Models/AzureFunctions.ts
- src/Models/IoTContainerizedProject.ts
- src/Models/IoTHub.ts
- src/Models/IoTHubDevice.ts
- src/Models/IoTWorkbenchProjectBase.ts
- src/Models/IoTWorkspaceProject.ts
- src/ProjectEnvironmentConfiger.ts
- src/utils.ts
Fix [bug](https://dev.azure.com/mseng/VSIoT/_workitems/edit/1679307):
When creating iot workspace project, steps sequence should be:
init components -> check prerequisites(will check dependent extensions) -> create componens.
This PR move all files creation after prerequisites are checked and satisfied. Thus project will NOT be created if prerequistes are not satisfied.
> Fix Arduino project lazy creation

- azure-pipelines.yml
Use "vsciotci" account token to run Azure Pipelines instead of personal token.
> Change github connection token to use public account

- package-lock.json
- package.json
- src/extension.ts
- src/telemetry.ts
1. update dependency "vscode-extension-telemetry" to version 0.1.6
2. set firstParty = true for TelemetryReporter.
3. use sendTelemetryErrorEvent to suppress sending error telemetry.
4. update property name of error.name from error to errorType for initDigitalTwinCommand.
> Suppress sending error telemetry

- package-lock.json
Issue root cause: When installing `node-usb-native` package, the dependent package `@serialport/bindings` somehow can not be successfully installed, which cause the failure of device setting configuration.
After updating the package-lock.json, `@serialport/bindings` package can be successfully installed, which resolves the bug.
> bug fix: configure device setting fails

- README.md
Changes
- Update the wording from Public Preview to Preview Refresh 
- Update the Overview, Get Started and Commands section to align with Workbench 0.16.0. Adding comments for old or deprecated contents.
> Update the Readme to align with Workbench 0.16.0
